<?php
// $Id$

/**
 * @file
 * This module provides a block and a settings page to display a collection
 * of social media links like Facebook, Twitter, Simplenews subscription, etc.
 */

/*******************************************************************************
 * Hook Functions (Drupal)
 ******************************************************************************/

/**
 * Implementation of hook_perm().
 */
function sociallinks_perm() {
  return array('access social links');
}

/**
 * Implementation of hook_block().
 */
function sociallinks_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info' => t('Social links'),
        'weight' => -10
      );
      return $blocks;
    case 'configure':
      if ($delta == 0) {
        sociallinks_include_files();
        $tabs = sociallinks_fetch_tabs(FALSE, TRUE);
        $form['sociallinks_tabs'] = array('#tree' => TRUE);
        foreach ($tabs as $id => $tab) {
          $form['sociallinks_tabs'][$id] = array(
            '#type' => 'fieldset',
            '#title' => $tab['title'] .' tab settings',
            '#collapsible' => TRUE,
            '#collapsed' => TRUE
          );
          $form['sociallinks_tabs'][$id]['enabled'] = array(
            '#type' => 'checkbox',
            '#title' => t('Enabled'),
            '#default_value' => $tab['settings']['enabled']
          );
          $form['sociallinks_tabs'][$id]['title'] = array(
            '#type' => 'textfield',
            '#title' => t('Tab Title'),
            '#description' => t('Override the default title for the tab. Leave blank to use the default tab title.'),
            '#default_value' => $tab['settings']['title']
          );
          $form['sociallinks_tabs'][$id]['message'] = array(
            '#type' => 'textarea',
            '#title' => t('Message'),
            '#description' => t('Enter a message to be displayed in the content of the tab.'),
            '#default_value' => $tab['settings']['message'],
            '#rows' => 10
          );
          $form['sociallinks_tabs'][$id]['weight'] = array(
            '#type' => 'weight',
            '#title' => t('Weight'),
            '#delta' => 10,
            '#default_value' => $tab['settings']['weight'],
            '#weight' => 10
          );
          if (isset($tab['configure callback'])) {
            $function = $tab['configure callback'];
            $form['sociallinks_tabs'][$id] += $function();
          }
        }
        return $form;
      }
    case 'save':
      if ($delta == 0) {
        $settings = array();
        sociallinks_include_files();
        $tabs = sociallinks_fetch_tabs(FALSE, TRUE);
        foreach ($edit['sociallinks_tabs'] as $id => $tab) {
          if (isset($tabs[$id]['save callback'])) {
            $function = $tabs[$id]['save callback'];
            $enabled = $function($edit['sociallinks_tabs'][$id]);
          }
          $settings[$id]['enabled'] = ($enabled !== FALSE) ? $tab['enabled'] : FALSE;
          $settings[$id]['title'] = $tab['title'];
          $settings[$id]['message'] = $tab['message'];
          $settings[$id]['weight'] = $tab['weight'];
        }
        variable_set('sociallinks_global_tab_settings', $settings);
        cache_clear_all('sociallinks:tabs', 'cache');
      }
      break;
    case 'view': default:
      switch ($delta) {
        case 0:
          if (user_access('access social links')) {
            $block['subject'] = t('Social links');
            $block['content'] = theme('sociallinks_block');
            return $block;
          }
      }
  }
}

/**
 * Implementation of hook_theme().
 */
function sociallinks_theme() {
  return array(
    'sociallinks_block' => array(
      'arguments' => array('tabs' => '', 'content' => ''),
      'template' => 'sociallinks-block',
    ),
    'sociallinks_tab' => array(
      'arguments' => array('tab' => NULL)
    ),
    'sociallinks_content' => array(
      'arguments' => array('tab' => NULL, 'output' => NULL)
    )
  );
}

/*******************************************************************************
 * Hook Functions (Social Links)
 ******************************************************************************/

function sociallinks_sociallinks_tabs() {
  return array(
    'facebook' => array(
      'title' => 'Facebook',
      'file' => 'sociallinks.tabs.inc',
      'configure callback' => 'sociallinks_facebook_configure'
    ),
    'twitter' => array(
      'title' => 'Twitter',
      'file' => 'sociallinks.tabs.inc',
      'configure callback' => 'sociallinks_twitter_configure'
    )
  );
}

/*******************************************************************************
 * Callback Functions, Forms, and Tables
 ******************************************************************************/



/*******************************************************************************
 * Module and Helper Functions
 ******************************************************************************/

function sociallinks_fetch_tabs($enabled = FALSE, $rebuild = FALSE) {
  static $tabs = array();

  if ($rebuild) {
    $tabs = array();
  }

  if (empty($tabs)) {
    if (!$rebuild) {
      $cache = cache_get('sociallinks:tabs');
      if (!empty($cache->data)) {
        $tabs = $cache->data;
      }
    }

    if (empty($tabs)) {
      foreach (module_implements('sociallinks_tabs') as $module) {
        $function = $module .'_sociallinks_tabs';
        $module_tabs = $function();

        // Add defaults if needed.
        foreach ($module_tabs as $id => $tab) {
          $module_tabs[$id]['module'] = $module;
          $module_tabs[$id]['id'] = $id;
          if (!isset($tab['settings']['enabled'])) {
            $module_tabs[$id]['settings']['enabled'] = FALSE;
          }
          if (!isset($tab['settings']['title'])) {
            $module_tabs[$id]['settings']['title'] = '';
          }
          if (!isset($tab['settings']['message'])) {
            $module_tabs[$id]['settings']['message'] = '';
          }
          if (!isset($tab['settings']['weight'])) {
            $module_tabs[$id]['settings']['weight'] = 0;
          }
          if (isset($tab['file']) && !isset($tab['file path'])) {
            $module_tabs[$id]['file path'] = drupal_get_path('module', $module);
          }
          if (isset($tab['configure callback'])) {
            if (!isset($tab['save callback'])) {
              $module_tabs[$id]['save callback'] = $module .'_'. $id .'_save';
            }
            if (!isset($tab['content callback'])) {
              $module_tabs[$id]['content callback'] = $module .'_'. $id .'_content';
            }
          }
        }

        $tabs += $module_tabs;
      }

      drupal_alter('sociallinks_tabs_alter', $tabs);

      // Apply settings
      $settings = variable_get('sociallinks_global_tab_settings', array());
      foreach ($settings as $id => $tab) {
        $tabs[$id]['settings'] = array_merge($tabs[$id]['settings'], $tab);
      }

      cache_set('sociallinks:tabs', $tabs);
    }
  }

  uasort($tabs, "sociallinks_tab_sort");

  if ($enabled) {
    $enabled_tabs = array();
    foreach ($tabs as $tab) {
      if ($tab['settings']['enabled'] && module_exists($tab['module'])) {
        $enabled_tabs[] = $tab;
      }
    }
    return $enabled_tabs;
  }

  return $tabs;
}

function sociallinks_include_files($include_tabs = array()) {
  $tabs = sociallinks_fetch_tabs();

  if (empty($include_tabs)) {
    $include_tabs = array_keys($tabs);
  }

  foreach ($include_tabs as $id) {
    if (!isset($included[$id]) && isset($tabs[$id]['file'])) {
      sociallinks_include($tabs[$id]['file'], $tabs[$id]['file path']);
    }
  }
}

function sociallinks_include($file, $path) {
  static $included = array();

  if (!isset($included[$path .'/'. $file])) {
    if (isset($file) && file_exists('./'. $path .'/'. $file)) {
      require_once './' . $path .'/'. $file;
    }
    $included[$id] = TRUE;
  }
}

function sociallinks_get_output() {
  $tabs = $content = array();
  foreach (sociallinks_fetch_tabs(TRUE) as $tab) {
    $output = $tab['settings']['message'];
    if (isset($tab['content callback'])) {
      if (isset($tab['file'])) {
        sociallinks_include($tab['file'], $tab['file path']);
      }
      $function = $tab['content callback'];
      if (function_exists($function)) {
        $output .= $function();
      }
    }
    $tabs[] = array(
      '#value' => theme('sociallinks_tab', $tab),
      '#weight' => $tab['settings']['weight']
    );
    $content[] = array(
      '#value' => theme('sociallinks_content', $tab, $output),
      '#weight' => $tab['settings']['weight']
    );
  }
  return array($tabs, $content);
}

function sociallinks_tab_sort($a, $b) {
  $a_weight = $a['settings']['weight'];
  $b_weight = $b['settings']['weight'];
  if ($a_weight == $b_weight) {
    $a_title = (!empty($a['settings']['title'])) ? $a['settings']['title'] : $a['title'];
    $b_title = (!empty($b['settings']['title'])) ? $b['settings']['title'] : $b['title'];
    if ($a_title == $b_title) {
      return 0;
    }
    return strcmp($a_title, $b_title);
  }
  return ($a_weight < $b_weight) ? -1 : 1;
}

/*******************************************************************************
 * Theme Functions
 ******************************************************************************/

function template_preprocess_sociallinks_block(&$vars) {
  jquery_ui_add('ui.tabs');
  drupal_add_js(drupal_get_path('module', 'sociallinks') .'/sociallinks.js');
  drupal_add_css(drupal_get_path('module', 'sociallinks') .'/sociallinks.css');

  list($vars['tabs'], $vars['content']) = sociallinks_get_output();
}

function theme_sociallinks_tab($tab) {
  $title = (!empty($tab['settings']['title'])) ? $tab['settings']['title'] : $tab['title'];
  return '<li><a href="#sociallinks-tab-'. str_replace('_', '-', $tab['id']) .'"><span>'. $title .'</span></a></li>';
}

function theme_sociallinks_content($tab, $output) {
  return '<div id="sociallinks-tab-'. str_replace('_', '-', $tab['id']) .'" class="sociallinks-content">'. $output .'</div>';
}
